### PR TITLE
Connect "Create Issue" to backend

### PR DESCRIPTION
**Pull request by sklirg**
This makes it possible to create issues in the frontend and persist it in the backend.

Notes:
* The issue creation should be refactored into using pure react state, rather than redux, since it's not to be used outside of this page. Therefore, some of the functionality (options and vote demand) does not impact it at the moment. 

What works nicely, though, is the text area (issue description) and either Y/N questions or multiple choice answers (it's not possible to remove custom answers at the moment either, because of the pending refactor).

### CODE REVIEW

**Comment by sklirg** [comment]
Refactored most of the component to use local state rather than redux.

Also added a warning if there is an active issue already.

screenshot 2017-03-09 15 53 24

**Comment by torjusti** [comment]
> Refactored most of the component to use local state rather than redux.

Do you want all the components related to the create issue form to use local state instead of redux?

**Comment by sklirg** [comment]
> Do you want all the components related to the create issue form to use local state instead of redux?

Yes, if it's not required somewhere else in the application, it's unnecessarily complex to keep the state in redux imo.

**Comment by torjusti** [comment]
I think I've more or less completed that refactoring now. I also think you intended to remove the SelectQuestionType-component. I think this is a good idea, but I haven't done it yet.

**Pull request merged**
